version: "3.8"
services:
    db:
        image: postgres:12-alpine
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        environment:
          - POSTGRES_USER=groover_challenge
          - POSTGRES_PASSWORD=groover_challenge
          - POSTGRES_DB=groover_challenge
        logging:
            driver: "none"
    webserver:
        build: .
        command: python manage.py run -h 0.0.0.0
        volumes:
            - ./:/app
        ports:
            - "5000:5000"
        links:
            - db
        env_file:
            - .env

volumes:
    postgres_data: